# Generated by Django 2.1.7 on 2019-04-02 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField(verbose_name="desde")),
                ("to_date", models.DateField(verbose_name="hasta")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="notas"),
                ),
                (
                    "rooms",
                    models.ManyToManyField(
                        related_name="reservations",
                        to="rooms.Room",
                        verbose_name="Habitación reservada",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["from_date", "to_date"],
            },
        )
    ]
