# Generated by Django 2.1.7 on 2019-03-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reservations", "0002_auto_20190304_1546")]

    operations = [
        migrations.RenameField(
            model_name="reservation", old_name="notas", new_name="notes"
        )
    ]
